languages:
  - code: en
    name: English
    direction: ltr
    font: "Times New Roman"
    metadata:
      lang: en-US

  - code: ar
    name: Arabic
    direction: rtl
    font: Amiri
    metadata:
      lang: ar
      dir: rtl

documentation:
  outputFormats:
    - pdf
    - html
  basePath: docs/
  structure:
    - title: Introduction
      path: docs/intro.md
    - title: Top 10 Risks
      path: docs/risks/
      children:
        - title: Risk 1
          path: docs/risks/risk1.md
        - title: Risk 2
          path: docs/risks/risk2.md
  metadata:
    version: "1.0.0"
    status: "draft"
    lastUpdated: "2024-02-20"
    nextReview: "2024-08-20"

templates:
  en: templates/default.tex
  ar: templates/arabic.tex

validation:
  rules:
    - no-broken-links
    - spelling
    - formatting
  exclusions:
    - node_modules
    - .git
  minWordCount: 100
  maxWordCount: 5000

build:
  parallel: true
  cacheEnabled: true
  outputDir: dist/

versioning:
  strategy: semver
  branches:
    - main
    - develop
    - release/*
  tagPrefix: v
  generateChangelog: true

lifecycle:
  requiredReviewers: 2
  stages:
    - draft
    - technical-review
    - peer-review
    - final-review
    - published
  autoArchive: true
  retentionPeriod: 2y

security:
  roles:
    - name: admin
      permissions:
        - deploy
        - release
    - name: developer
      permissions:
        - build
        - test
        - commit
  auditLogging: true
  compliance:
    standards:
      - ISO27001
      - SOC2

logging:
  level: info
  format: json
  output: logs/app.log

monitoring:
  enabled: true
  endpoint: /metrics
  provider: prometheus
