name: GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install -g markdownlint-cli
          npm install -g @vuepress/core@next @vuepress/client@next
          npm install -g vuepress@next

      - name: Build Documentation
        run: |
          # Create VuePress config
          mkdir -p docs/.vuepress
          cat > docs/.vuepress/config.js << EOL
          import { defineUserConfig } from 'vuepress'
          import { defaultTheme } from '@vuepress/theme-default'

          export default defineUserConfig({
            lang: 'en-US',
            title: 'OWASP Top 10 for AI Agents',
            description: 'Security risks and best practices for AI Agents',
            theme: defaultTheme({
              repo: 'OWASP/Top-10-for-AI-Agents',
              docsDir: 'docs',
              editLink: true,
              navbar: [
                { text: 'Home', link: '/' },
                { text: 'Guide', link: '/guide/' },
                { text: 'Risks', link: '/risks/' },
                { text: 'Glossary', link: '/glossary/' }
              ]
            })
          })
          EOL

          # Copy content
          mkdir -p docs/guide docs/risks docs/glossary
          cp README.md docs/index.md
          cp -r v1/translations/en/* docs/risks/
          cp -r v1/glossary/markdown/* docs/glossary/

          # Build site
          vuepress build docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vuepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
